s1 = {1, 5, 2, 3, 4, 1}
print(f"Initialize directly : {s1}")
s2 = set()
s2.add(24)
s2.add(30)
s2.add(11)
print(f"Initialized empty : {s2}")
s3 = set([1, 42, 33, 9, 10])
print(f"Set Initialized from list : {s3}")
s2 = set({4, 8, -9, 22})
print(f"Set Initialized form set : {s2}")
s2 = set(range(5))
print(f"Set Initialized using Range : {s2}")
s3.update(s2)
print(f"Updated set using another set : {s3}")
print(f"Printing set Iteratively : ", end="")
for i in s1: print(i, end=" ")
s1.remove(5)
print(f"\ns1.remove(5) : {s1}")
s1.discard(3)
print(f"s1.discard(3) : {s1}")
