import Head from 'next/head';
import Navbar from '@/components/Navbar'
import LeftSide from '@/components/LeftSide';
import RightSide from '@/components/RightSide';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-bodyColor font-bodyFont text-textLight overflow-x-hidden overflow-y-scroll h-screen w-full'>
        <Navbar />
        <div className='w-full h-[88vh] xl:flex items-center gap-20 justify-between'>
          <div className='hidden xl:inline-flex w-32 h-full left-0 bottom-0 fixed'> <LeftSide /> </div>
          <div className='h-[88vh] mx-auto p-4'>Middle</div>
          <div className='hidden xl:inline-flex w-32 h-full fixed right-0 bottom-0'> <RightSide /> </div>
        </div>
      </main>
    </>
  )
}
