import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Blogstop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <h1 className={styles.name}>Blogstop</h1>
        </div>
        <hr className={styles.horLine} />
        <div>
          <h2 className={styles.subtitle}>Recent Blogs</h2>
          <div className="blogcontainer">
            <div className={styles.blog}>
              <h3 className={styles.blogtitle}>Indian foreign policy</h3>
              <p className={styles.content} style={{ paddingBottom: '0px' }}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores odit deserunt qui officiis minus dolorem labore, itaque quo, aperiam ea totam fuga magni obcaecati quibusdam quaerat eaque. Dolore, beatae exercitationem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis in libero asperiores et esse optio tenetur, nisi sequi neque voluptatum earum vel veritatis mollitia blanditiis labore voluptatibus vero sit quasi! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt nam qui veniam fugiat. Dolores perspiciatis consequuntur nihil consequatur, corrupti similique aut ipsam alias, cum numquam odio accusamus deserunt dolor. Eius.</p><br />
              <p className={styles.content}>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor quod cupiditate officia, aperiam, dignissimos mollitia voluptates, delectus in possimus vero quisquam non sint voluptate cumque provident. Eaque consequuntur quos ipsa.</p>
            </div>
            <div className={styles.blog}>
              <h3 className={styles.blogtitle}>Education system of India</h3>
              <p className={styles.content}>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor quod cupiditate officia, aperiam, dignissimos mollitia voluptates, delectus in possimus vero quisquam non sint voluptate cumque provident. Eaque consequuntur quos ipsa.</p>
              <p className={styles.content} style={{ paddingBottom: '0px' }}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores odit deserunt qui officiis minus dolorem labore, itaque quo, aperiam ea totam fuga magni obcaecati quibusdam quaerat eaque. Dolore, beatae exercitationem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis in libero asperiores et esse optio tenetur, nisi sequi neque voluptatum earum vel veritatis mollitia blanditiis labore voluptatibus vero sit quasi! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt nam qui veniam fugiat. Dolores perspiciatis consequuntur nihil consequatur, corrupti similique aut ipsam alias, cum numquam odio accusamus deserunt dolor. Eius.</p><br />
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
